# Generated by Django 3.2.8 on 2021-11-30 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('count', models.IntegerField()),
                ('median', models.FloatField()),
                ('mean', models.FloatField()),
                ('polarity', models.FloatField()),
                ('sum', models.FloatField()),
                ('bitcoin_price', models.FloatField()),
                ('date_time', models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 30, 9, 46, 32, 303570))),
            ],
        ),
    ]
