# Generated by Django 3.2.8 on 2021-11-30 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sentimentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentdata',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 30, 9, 48, 50, 432495)),
        ),
    ]
