# Generated by Django 3.2.8 on 2021-11-30 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sentimentdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentdata',
            name='bitcoin_price',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sentimentdata',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 30, 9, 50, 36, 123206)),
        ),
    ]
