# Generated by Django 3.2.8 on 2021-11-30 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sentimentdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentdata',
            name='btc_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentimentdata',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 30, 10, 1, 21, 713414)),
        ),
    ]
