# Generated by Django 3.2.8 on 2021-11-30 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sentimentdata_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentdata',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentdata',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 30, 10, 10, 49, 235962)),
        ),
    ]
